#!/bin/sh
#
# Startup script for the Keepalived daemon
#
# processname: keepalived
# pidfile: /var/run/keepalived.pid
# config: /etc/keepalived/keepalived.conf
# chkconfig: - 21 79
# description: Start and stop Keepalived

# Source function library
#. /etc/rc.d/init.d/functions

# Source configuration file (we set KEEPALIVED_OPTIONS there)
#. /etc/sysconfig/keepalived-vip

#RETVAL=0

#prog="keepalived-vip"

#start() {
#    echo -n $"Starting $prog: "
#    daemon kube-keepalived-vip.sh
#    RETVAL=$?
#    echo
#    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
#}
#
#stop() {
#    echo -n $"Stopping $prog: "
#    pid=`ps -ef|grep keepalived|grep -v grep|awk '{print $2}'`
#    #kill -TERM $pid
#    killproc keepalived 
#    #&& killproc keepalived
#    RETVAL=$?
#    echo
#    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
#}

#reload() {
#    echo -n $"Reloading $prog: "
#    killproc keepalived -1
#    RETVAL=$?
#    echo
#}

# See how we were called.
case "$1" in
    start)
        start keepalived-vip
        ;;
    stop)
        stop keepalived-vip
        ;;
    reload)
        reload keepalived-vip
        ;;
    restart)
        stop keepalived-vip
        start keepalived-vip
        ;;
    condrestart)
        #if [ -f /var/lock/subsys/$prog ]; then
        stop keepalived-vip
        start keepalived-vip
        #fi
        ;;
    status)
        status keepalived-vip
        ;;
    *)
        echo "Usage: $0 {start|stop|reload|restart|condrestart|status}"
        exit 1
esac
RETVAL=0
exit $RETVAL
